//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDecide.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultChoices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultChoices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDecide.Localization.DefaultChoices", typeof(DefaultChoices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head or Tail.
        /// </summary>
        internal static string HeadTail {
            get {
                return ResourceManager.GetString("HeadTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizard.
        /// </summary>
        internal static string Lizard {
            get {
                return ResourceManager.GetString("Lizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Ball.
        /// </summary>
        internal static string MagicBall {
            get {
                return ResourceManager.GetString("MagicBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As I see it, yes.
        /// </summary>
        internal static string MagicBall1 {
            get {
                return ResourceManager.GetString("MagicBall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may rely on it.
        /// </summary>
        internal static string MagicBall10 {
            get {
                return ResourceManager.GetString("MagicBall10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply hazy, try again.
        /// </summary>
        internal static string MagicBall11 {
            get {
                return ResourceManager.GetString("MagicBall11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask again later.
        /// </summary>
        internal static string MagicBall12 {
            get {
                return ResourceManager.GetString("MagicBall12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better not tell you now.
        /// </summary>
        internal static string MagicBall13 {
            get {
                return ResourceManager.GetString("MagicBall13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot predict now.
        /// </summary>
        internal static string MagicBall14 {
            get {
                return ResourceManager.GetString("MagicBall14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentrate and ask again.
        /// </summary>
        internal static string MagicBall15 {
            get {
                return ResourceManager.GetString("MagicBall15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t count on it.
        /// </summary>
        internal static string MagicBall16 {
            get {
                return ResourceManager.GetString("MagicBall16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reply is no.
        /// </summary>
        internal static string MagicBall17 {
            get {
                return ResourceManager.GetString("MagicBall17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My sources say no.
        /// </summary>
        internal static string MagicBall18 {
            get {
                return ResourceManager.GetString("MagicBall18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook not so good.
        /// </summary>
        internal static string MagicBall19 {
            get {
                return ResourceManager.GetString("MagicBall19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is certain.
        /// </summary>
        internal static string MagicBall2 {
            get {
                return ResourceManager.GetString("MagicBall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very doubtful.
        /// </summary>
        internal static string MagicBall20 {
            get {
                return ResourceManager.GetString("MagicBall20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is decidedly so.
        /// </summary>
        internal static string MagicBall3 {
            get {
                return ResourceManager.GetString("MagicBall3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most likely.
        /// </summary>
        internal static string MagicBall4 {
            get {
                return ResourceManager.GetString("MagicBall4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook good.
        /// </summary>
        internal static string MagicBall5 {
            get {
                return ResourceManager.GetString("MagicBall5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signs point to yes.
        /// </summary>
        internal static string MagicBall6 {
            get {
                return ResourceManager.GetString("MagicBall6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without a doubt.
        /// </summary>
        internal static string MagicBall7 {
            get {
                return ResourceManager.GetString("MagicBall7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MagicBall8 {
            get {
                return ResourceManager.GetString("MagicBall8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes – definitely.
        /// </summary>
        internal static string MagicBall9 {
            get {
                return ResourceManager.GetString("MagicBall9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe.
        /// </summary>
        internal static string Maybe {
            get {
                return ResourceManager.GetString("Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock-Paper-Scissor-Lizard-Spock.
        /// </summary>
        internal static string RPSLS {
            get {
                return ResourceManager.GetString("RPSLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scissor.
        /// </summary>
        internal static string Scissor {
            get {
                return ResourceManager.GetString("Scissor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spock.
        /// </summary>
        internal static string Spock {
            get {
                return ResourceManager.GetString("Spock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail.
        /// </summary>
        internal static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, No, Maybe?.
        /// </summary>
        internal static string YesNoMaybe {
            get {
                return ResourceManager.GetString("YesNoMaybe", resourceCulture);
            }
        }
    }
}
