//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scudetti.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShieldResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShieldResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scudetti.Localization.ShieldResources", typeof(ShieldResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aek Atene.
        /// </summary>
        public static string AekAtene {
            get {
                return ResourceManager.GetString("AekAtene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aik Stockholm.
        /// </summary>
        public static string AikStockholm {
            get {
                return ResourceManager.GetString("AikStockholm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajax.
        /// </summary>
        public static string Ajax {
            get {
                return ResourceManager.GetString("Ajax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amburgo.
        /// </summary>
        public static string Amburgo {
            get {
                return ResourceManager.GetString("Amburgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderlecht.
        /// </summary>
        public static string Anderlecht {
            get {
                return ResourceManager.GetString("Anderlecht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzhi Makhachkala.
        /// </summary>
        public static string AnzhiMakhachkala {
            get {
                return ResourceManager.GetString("AnzhiMakhachkala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsenal.
        /// </summary>
        public static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aston Villa.
        /// </summary>
        public static string AstonVilla {
            get {
                return ResourceManager.GetString("AstonVilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atletico Bilbao.
        /// </summary>
        public static string AtleticoBilbao {
            get {
                return ResourceManager.GetString("AtleticoBilbao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atletico Madrid.
        /// </summary>
        public static string AtleticoMadrid {
            get {
                return ResourceManager.GetString("AtleticoMadrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxerre.
        /// </summary>
        public static string Auxerre {
            get {
                return ResourceManager.GetString("Auxerre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az Alkmaar.
        /// </summary>
        public static string AzAlkmaar {
            get {
                return ResourceManager.GetString("AzAlkmaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcelona.
        /// </summary>
        public static string Barcelona {
            get {
                return ResourceManager.GetString("Barcelona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basilea.
        /// </summary>
        public static string Basilea {
            get {
                return ResourceManager.GetString("Basilea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bate Borisov.
        /// </summary>
        public static string BateBorisov {
            get {
                return ResourceManager.GetString("BateBorisov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayer Leverkusen.
        /// </summary>
        public static string BayerLeverkusen {
            get {
                return ResourceManager.GetString("BayerLeverkusen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayern Monaco.
        /// </summary>
        public static string BayernMonaco {
            get {
                return ResourceManager.GetString("BayernMonaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benfica.
        /// </summary>
        public static string Benfica {
            get {
                return ResourceManager.GetString("Benfica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besiktas.
        /// </summary>
        public static string Besiktas {
            get {
                return ResourceManager.GetString("Besiktas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birmingham City.
        /// </summary>
        public static string BirminghamCity {
            get {
                return ResourceManager.GetString("BirminghamCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackburn Rovers.
        /// </summary>
        public static string BlackburnRovers {
            get {
                return ResourceManager.GetString("BlackburnRovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boavista.
        /// </summary>
        public static string Boavista {
            get {
                return ResourceManager.GetString("Boavista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boca Juniors.
        /// </summary>
        public static string BocaJuniors {
            get {
                return ResourceManager.GetString("BocaJuniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bochum.
        /// </summary>
        public static string Bochum {
            get {
                return ResourceManager.GetString("Bochum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordeaux.
        /// </summary>
        public static string Bordeaux {
            get {
                return ResourceManager.GetString("Bordeaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borussia Dortmund.
        /// </summary>
        public static string BorussiaDortmund {
            get {
                return ResourceManager.GetString("BorussiaDortmund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celta Vigo.
        /// </summary>
        public static string CeltaVigo {
            get {
                return ResourceManager.GetString("CeltaVigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celtic.
        /// </summary>
        public static string Celtic {
            get {
                return ResourceManager.GetString("Celtic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cglasgow Rangers.
        /// </summary>
        public static string CglasgowRangers {
            get {
                return ResourceManager.GetString("CglasgowRangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chelsea.
        /// </summary>
        public static string Chelsea {
            get {
                return ResourceManager.GetString("Chelsea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Brugge.
        /// </summary>
        public static string ClubBrugge {
            get {
                return ResourceManager.GetString("ClubBrugge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluj.
        /// </summary>
        public static string Cluj {
            get {
                return ResourceManager.GetString("Cluj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colo Colo.
        /// </summary>
        public static string ColoColo {
            get {
                return ResourceManager.GetString("ColoColo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copenaghen.
        /// </summary>
        public static string Copenaghen {
            get {
                return ResourceManager.GetString("Copenaghen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corinthians.
        /// </summary>
        public static string Corinthians {
            get {
                return ResourceManager.GetString("Corinthians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Palace.
        /// </summary>
        public static string CrystalPalace {
            get {
                return ResourceManager.GetString("CrystalPalace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cska Mosca.
        /// </summary>
        public static string CskaMosca {
            get {
                return ResourceManager.GetString("CskaMosca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cska Sofia.
        /// </summary>
        public static string CskaSofia {
            get {
                return ResourceManager.GetString("CskaSofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deportivo La Coruna.
        /// </summary>
        public static string DeportivoLaCoruna {
            get {
                return ResourceManager.GetString("DeportivoLaCoruna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derby County.
        /// </summary>
        public static string DerbyCounty {
            get {
                return ResourceManager.GetString("DerbyCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinamo Zagabria.
        /// </summary>
        public static string DinamoZagabria {
            get {
                return ResourceManager.GetString("DinamoZagabria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Kiev.
        /// </summary>
        public static string DynamoKiev {
            get {
                return ResourceManager.GetString("DynamoKiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintracht Francoforte.
        /// </summary>
        public static string EintrachtFrancoforte {
            get {
                return ResourceManager.GetString("EintrachtFrancoforte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fc Porto.
        /// </summary>
        public static string FcPorto {
            get {
                return ResourceManager.GetString("FcPorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenerbahce.
        /// </summary>
        public static string Fenerbahce {
            get {
                return ResourceManager.GetString("Fenerbahce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feyenoord.
        /// </summary>
        public static string Feyenoord {
            get {
                return ResourceManager.GetString("Feyenoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiorentina.
        /// </summary>
        public static string Fiorentina {
            get {
                return ResourceManager.GetString("Fiorentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamengo.
        /// </summary>
        public static string Flamengo {
            get {
                return ResourceManager.GetString("Flamengo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulham.
        /// </summary>
        public static string Fulham {
            get {
                return ResourceManager.GetString("Fulham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galatasaray.
        /// </summary>
        public static string Galatasaray {
            get {
                return ResourceManager.GetString("Galatasaray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galaxy.
        /// </summary>
        public static string Galaxy {
            get {
                return ResourceManager.GetString("Galaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genoa.
        /// </summary>
        public static string Genoa {
            get {
                return ResourceManager.GetString("Genoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goteborg.
        /// </summary>
        public static string Goteborg {
            get {
                return ResourceManager.GetString("Goteborg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grasshoppers.
        /// </summary>
        public static string Grasshoppers {
            get {
                return ResourceManager.GetString("Grasshoppers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guangzhou Evergrande.
        /// </summary>
        public static string GuangzhouEvergrande {
            get {
                return ResourceManager.GetString("GuangzhouEvergrande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hajduk Split.
        /// </summary>
        public static string HajdukSplit {
            get {
                return ResourceManager.GetString("HajdukSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        public static string Hearts {
            get {
                return ResourceManager.GetString("Hearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heerenveen.
        /// </summary>
        public static string Heerenveen {
            get {
                return ResourceManager.GetString("Heerenveen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independiente.
        /// </summary>
        public static string Independiente {
            get {
                return ResourceManager.GetString("Independiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter.
        /// </summary>
        public static string Inter {
            get {
                return ResourceManager.GetString("Inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jherta Berlino.
        /// </summary>
        public static string JhertaBerlino {
            get {
                return ResourceManager.GetString("JhertaBerlino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jubilo Iwata.
        /// </summary>
        public static string JubiloIwata {
            get {
                return ResourceManager.GetString("JubiloIwata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juventus.
        /// </summary>
        public static string Juventus {
            get {
                return ResourceManager.GetString("Juventus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazio.
        /// </summary>
        public static string Lazio {
            get {
                return ResourceManager.GetString("Lazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeds.
        /// </summary>
        public static string Leeds {
            get {
                return ResourceManager.GetString("Leeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lille.
        /// </summary>
        public static string Lille {
            get {
                return ResourceManager.GetString("Lille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liverpool.
        /// </summary>
        public static string Liverpool {
            get {
                return ResourceManager.GetString("Liverpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maccabi.
        /// </summary>
        public static string Maccabi {
            get {
                return ResourceManager.GetString("Maccabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manchester City.
        /// </summary>
        public static string ManchesterCity {
            get {
                return ResourceManager.GetString("ManchesterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manchester United.
        /// </summary>
        public static string ManchesterUnited {
            get {
                return ResourceManager.GetString("ManchesterUnited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maribor.
        /// </summary>
        public static string Maribor {
            get {
                return ResourceManager.GetString("Maribor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechelen.
        /// </summary>
        public static string Mechelen {
            get {
                return ResourceManager.GetString("Mechelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalist.
        /// </summary>
        public static string Metalist {
            get {
                return ResourceManager.GetString("Metalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milan.
        /// </summary>
        public static string Milan {
            get {
                return ResourceManager.GetString("Milan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monacò.
        /// </summary>
        public static string Monacò {
            get {
                return ResourceManager.GetString("Monacò", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco 1869.
        /// </summary>
        public static string Monaco1869 {
            get {
                return ResourceManager.GetString("Monaco1869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nantes.
        /// </summary>
        public static string Nantes {
            get {
                return ResourceManager.GetString("Nantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napoli.
        /// </summary>
        public static string Napoli {
            get {
                return ResourceManager.GetString("Napoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newcastle.
        /// </summary>
        public static string Newcastle {
            get {
                return ResourceManager.GetString("Newcastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nottingham Forest.
        /// </summary>
        public static string NottinghamForest {
            get {
                return ResourceManager.GetString("NottinghamForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odense.
        /// </summary>
        public static string Odense {
            get {
                return ResourceManager.GetString("Odense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympiakos.
        /// </summary>
        public static string Olympiakos {
            get {
                return ResourceManager.GetString("Olympiakos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympique Lione.
        /// </summary>
        public static string OlympiqueLione {
            get {
                return ResourceManager.GetString("OlympiqueLione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympique Marsiglia.
        /// </summary>
        public static string OlympiqueMarsiglia {
            get {
                return ResourceManager.GetString("OlympiqueMarsiglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palermo.
        /// </summary>
        public static string Palermo {
            get {
                return ResourceManager.GetString("Palermo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palmeiras.
        /// </summary>
        public static string Palmeiras {
            get {
                return ResourceManager.GetString("Palmeiras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paris Saint Germain.
        /// </summary>
        public static string ParisSaintGermain {
            get {
                return ResourceManager.GetString("ParisSaintGermain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partizan Belgrado.
        /// </summary>
        public static string PartizanBelgrado {
            get {
                return ResourceManager.GetString("PartizanBelgrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portsmouth.
        /// </summary>
        public static string Portsmouth {
            get {
                return ResourceManager.GetString("Portsmouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psv Eindhoven.
        /// </summary>
        public static string PsvEindhoven {
            get {
                return ResourceManager.GetString("PsvEindhoven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queens Park Rangers.
        /// </summary>
        public static string QueensParkRangers {
            get {
                return ResourceManager.GetString("QueensParkRangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing Santander.
        /// </summary>
        public static string RacingSantander {
            get {
                return ResourceManager.GetString("RacingSantander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Vienna.
        /// </summary>
        public static string RapidVienna {
            get {
                return ResourceManager.GetString("RapidVienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Madrid.
        /// </summary>
        public static string RealMadrid {
            get {
                return ResourceManager.GetString("RealMadrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Saragozza.
        /// </summary>
        public static string RealSaragozza {
            get {
                return ResourceManager.GetString("RealSaragozza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Sociedad.
        /// </summary>
        public static string RealSociedad {
            get {
                return ResourceManager.GetString("RealSociedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Plate.
        /// </summary>
        public static string RiverPlate {
            get {
                return ResourceManager.GetString("RiverPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roma.
        /// </summary>
        public static string Roma {
            get {
                return ResourceManager.GetString("Roma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosenborg.
        /// </summary>
        public static string Rosenborg {
            get {
                return ResourceManager.GetString("Rosenborg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubin Kazan.
        /// </summary>
        public static string RubinKazan {
            get {
                return ResourceManager.GetString("RubinKazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santos.
        /// </summary>
        public static string Santos {
            get {
                return ResourceManager.GetString("Santos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shakhtar Donetsk.
        /// </summary>
        public static string ShakhtarDonetsk {
            get {
                return ResourceManager.GetString("ShakhtarDonetsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shalke 04.
        /// </summary>
        public static string Shalke04 {
            get {
                return ResourceManager.GetString("Shalke04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheffield.
        /// </summary>
        public static string Sheffield {
            get {
                return ResourceManager.GetString("Sheffield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff Tiraspol.
        /// </summary>
        public static string SheriffTiraspol {
            get {
                return ResourceManager.GetString("SheriffTiraspol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siena.
        /// </summary>
        public static string Siena {
            get {
                return ResourceManager.GetString("Siena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siviglia.
        /// </summary>
        public static string Siviglia {
            get {
                return ResourceManager.GetString("Siviglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slavia Praga.
        /// </summary>
        public static string SlaviaPraga {
            get {
                return ResourceManager.GetString("SlaviaPraga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spartak Mosca.
        /// </summary>
        public static string SpartakMosca {
            get {
                return ResourceManager.GetString("SpartakMosca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparta Praga.
        /// </summary>
        public static string SpartaPraga {
            get {
                return ResourceManager.GetString("SpartaPraga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Lisbona.
        /// </summary>
        public static string SportingLisbona {
            get {
                return ResourceManager.GetString("SportingLisbona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Liegi.
        /// </summary>
        public static string StandardLiegi {
            get {
                return ResourceManager.GetString("StandardLiegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steaua Bucarest.
        /// </summary>
        public static string SteauaBucarest {
            get {
                return ResourceManager.GetString("SteauaBucarest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stella Rossa.
        /// </summary>
        public static string StellaRossa {
            get {
                return ResourceManager.GetString("StellaRossa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoccarda.
        /// </summary>
        public static string Stoccarda {
            get {
                return ResourceManager.GetString("Stoccarda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torino.
        /// </summary>
        public static string Torino {
            get {
                return ResourceManager.GetString("Torino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tottenham Hotspurs.
        /// </summary>
        public static string TottenhamHotspurs {
            get {
                return ResourceManager.GetString("TottenhamHotspurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twente.
        /// </summary>
        public static string Twente {
            get {
                return ResourceManager.GetString("Twente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udinese.
        /// </summary>
        public static string Udinese {
            get {
                return ResourceManager.GetString("Udinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valensia.
        /// </summary>
        public static string Valensia {
            get {
                return ResourceManager.GetString("Valensia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werder Brema.
        /// </summary>
        public static string WerderBrema {
            get {
                return ResourceManager.GetString("WerderBrema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Ham.
        /// </summary>
        public static string WestHam {
            get {
                return ResourceManager.GetString("WestHam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfsburg.
        /// </summary>
        public static string Wolfsburg {
            get {
                return ResourceManager.GetString("Wolfsburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolverhampton.
        /// </summary>
        public static string Wolverhampton {
            get {
                return ResourceManager.GetString("Wolverhampton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young Boys.
        /// </summary>
        public static string YoungBoys {
            get {
                return ResourceManager.GetString("YoungBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenit.
        /// </summary>
        public static string Zenit {
            get {
                return ResourceManager.GetString("Zenit", resourceCulture);
            }
        }
    }
}
