//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgarbiMix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoundsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoundsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SgarbiMix.SoundsResources", typeof(SoundsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ateo_fasullo_ {
            get {
                return ResourceManager.GetStream("Ateo_fasullo_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Capra_ {
            get {
                return ResourceManager.GetStream("Capra_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Capra_ignorante_ {
            get {
                return ResourceManager.GetStream("Capra_ignorante_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Criminale_ {
            get {
                return ResourceManager.GetStream("Criminale_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Culattoni_raccomandati_ {
            get {
                return ResourceManager.GetStream("Culattoni_raccomandati_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream È_insopportabile_ {
            get {
                return ResourceManager.GetStream("È_insopportabile_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream E_tu_sei_un_pirla_ {
            get {
                return ResourceManager.GetStream("E_tu_sei_un_pirla_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream È_un_crimine_ {
            get {
                return ResourceManager.GetStream("È_un_crimine_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Fascista_ {
            get {
                return ResourceManager.GetStream("Fascista_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Io_sono_convinto_che_vi_debbano_licenziare {
            get {
                return ResourceManager.GetStream("Io_sono_convinto_che_vi_debbano_licenziare", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Legga_Dante__Legga_Manzoni_ {
            get {
                return ResourceManager.GetStream("Legga_Dante__Legga_Manzoni_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Leggi__Studia_ {
            get {
                return ResourceManager.GetStream("Leggi__Studia_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Lo_mangerei_vivo_ {
            get {
                return ResourceManager.GetStream("Lo_mangerei_vivo_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ma_guarda_che_roba_ {
            get {
                return ResourceManager.GetStream("Ma_guarda_che_roba_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Mi_state_sui_coglioni_di_principio_ {
            get {
                return ResourceManager.GetStream("Mi_state_sui_coglioni_di_principio_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Non_dire_cretinate_ {
            get {
                return ResourceManager.GetStream("Non_dire_cretinate_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Non_ha_mai_fatto_un_cazzo_in_vita_sua {
            get {
                return ResourceManager.GetStream("Non_ha_mai_fatto_un_cazzo_in_vita_sua", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ridicolo_ {
            get {
                return ResourceManager.GetStream("Ridicolo_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ridicolo_sei__e_lo_sei_sempre_stato_ {
            get {
                return ResourceManager.GetStream("Ridicolo_sei__e_lo_sei_sempre_stato_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sei_ignorante_come_una_capra_ {
            get {
                return ResourceManager.GetStream("Sei_ignorante_come_una_capra_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Vai_a_studiare_ {
            get {
                return ResourceManager.GetStream("Vai_a_studiare_", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Vergogna__Vergogna_ {
            get {
                return ResourceManager.GetStream("Vergogna__Vergogna_", resourceCulture);
            }
        }
    }
}
