//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SgarbiMix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoundsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoundsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SgarbiMix.SoundsResources", typeof(SoundsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ateo_fasullo1 {
            get {
                return ResourceManager.GetStream("Ateo_fasullo1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Capra_ignorante1 {
            get {
                return ResourceManager.GetStream("Capra_ignorante1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Capra1 {
            get {
                return ResourceManager.GetStream("Capra1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Criminale1 {
            get {
                return ResourceManager.GetStream("Criminale1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Culattoni_raccomandati1 {
            get {
                return ResourceManager.GetStream("Culattoni_raccomandati1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream È_insopportabile1 {
            get {
                return ResourceManager.GetStream("È_insopportabile1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream E_tu_sei_un_pirla1 {
            get {
                return ResourceManager.GetStream("E_tu_sei_un_pirla1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream È_un_crimine1 {
            get {
                return ResourceManager.GetStream("È_un_crimine1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Fascista1 {
            get {
                return ResourceManager.GetStream("Fascista1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Legga_Dante1_Legga_Manzoni1 {
            get {
                return ResourceManager.GetStream("Legga_Dante1_Legga_Manzoni1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Leggi1_Studia1 {
            get {
                return ResourceManager.GetStream("Leggi1_Studia1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Lo_mangerei_vivo1 {
            get {
                return ResourceManager.GetStream("Lo_mangerei_vivo1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ma_guarda_che_roba1 {
            get {
                return ResourceManager.GetStream("Ma_guarda_che_roba1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Mi_state_sui_coglioni_di_principio1 {
            get {
                return ResourceManager.GetStream("Mi_state_sui_coglioni_di_principio1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Non_dire_cretinate1 {
            get {
                return ResourceManager.GetStream("Non_dire_cretinate1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Non_ha_fatto_mai_un_cazzo {
            get {
                return ResourceManager.GetStream("Non_ha_fatto_mai_un_cazzo", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ridicolo_sei_e_lo_sei_sempre_stato1 {
            get {
                return ResourceManager.GetStream("Ridicolo_sei_e_lo_sei_sempre_stato1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ridicolo1 {
            get {
                return ResourceManager.GetStream("Ridicolo1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sei_ignorante_come_una_capra1 {
            get {
                return ResourceManager.GetStream("Sei_ignorante_come_una_capra1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Siete_da_licenziare1 {
            get {
                return ResourceManager.GetStream("Siete_da_licenziare1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Vai_a_studiare1 {
            get {
                return ResourceManager.GetStream("Vai_a_studiare1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Vergogna1_Vergogna1 {
            get {
                return ResourceManager.GetStream("Vergogna1_Vergogna1", resourceCulture);
            }
        }
    }
}
