//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheldonMix.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SheldonMix.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phrases are all already updated.
        /// </summary>
        public static string AlreadyUpdated {
            get {
                return ResourceManager.GetString("AlreadyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unofficial app for The Big Bang Theory fans.
        ///All trademarks and copyrights are property of CBS..
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is missing in this app?
        ///Please send us your suggestions,
        ///we definitely consider your feedback!
        ///Open the About Page and drop us a line
        ///by mail, Twitter or Facebook..
        /// </summary>
        public static string GetFeedback {
            get {
                return ResourceManager.GetString("GetFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading sounds list.
        /// </summary>
        public static string LoadingSoundsList {
            get {
                return ResourceManager.GetString("LoadingSoundsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, but you have to be connected to internet to download the sounds.
        ///Close, connect to internet, and reopen the app..
        /// </summary>
        public static string NoConnectionAvailable {
            get {
                return ResourceManager.GetString("NoConnectionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops! There is something wrong with the connection to the server...
        ///Try again in a few minutes.
        ///If still doesn&apos;t work, please contact me on Facebook (WP Mobile Entertainment).
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set every sound as Ringtone by
        ///long-pressing on the buttons!.
        /// </summary>
        public static string SetRingtoneTip {
            get {
                return ResourceManager.GetString("SetRingtoneTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop your music and hear what Sheldon have to say?.
        /// </summary>
        public static string StopMusic {
            get {
                return ResourceManager.GetString("StopMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBBT.
        /// </summary>
        public static string TBBT {
            get {
                return ResourceManager.GetString("TBBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating sound {0}/{1}.
        /// </summary>
        public static string UpdatingSounds {
            get {
                return ResourceManager.GetString("UpdatingSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zazzy.
        /// </summary>
        public static string Zazzy {
            get {
                return ResourceManager.GetString("Zazzy", resourceCulture);
            }
        }
    }
}
