//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayMe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayMe.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop counting and reset the timer?.
        /// </summary>
        public static string AlertStopCounting {
            get {
                return ResourceManager.GetString("AlertStopCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayMe.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances List.
        /// </summary>
        public static string AttendancesList {
            get {
                return ResourceManager.GetString("AttendancesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy it now!.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Pay.
        /// </summary>
        public static string CallPay {
            get {
                return ResourceManager.GetString("CallPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name:.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to eMail.
        /// </summary>
        public static string ExportToMail {
            get {
                return ResourceManager.GetString("ExportToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minutes.
        /// </summary>
        public static string FifteenMinutes {
            get {
                return ResourceManager.GetString("FifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minutes.
        /// </summary>
        public static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Hour.
        /// </summary>
        public static string HalfHour {
            get {
                return ResourceManager.GetString("HalfHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Payment.
        /// </summary>
        public static string HourlyPayment {
            get {
                return ResourceManager.GetString("HourlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income:.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Second.
        /// </summary>
        public static string OneSecond {
            get {
                return ResourceManager.GetString("OneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Minutes.
        /// </summary>
        public static string TenMinutes {
            get {
                return ResourceManager.GetString("TenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money update.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your trial is expired for today.
        ///You can open the app tomorrow or you can.
        /// </summary>
        public static string TrialExpiredDescription {
            get {
                return ResourceManager.GetString("TrialExpiredDescription", resourceCulture);
            }
        }
    }
}
