//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheldonMix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoundsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoundsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SheldonMix.SoundsResources", typeof(SoundsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] base1 {
            get {
                object obj = ResourceManager.GetObject("base1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] base2 {
            get {
                object obj = ResourceManager.GetObject("base2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] base3 {
            get {
                object obj = ResourceManager.GetObject("base3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_bazinga_1 {
            get {
                object obj = ResourceManager.GetObject("CLAS_bazinga_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_bazinga_you_ve_fallen_in_one_of_my_jokes {
            get {
                object obj = ResourceManager.GetObject("CLAS_bazinga_you_ve_fallen_in_one_of_my_jokes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_change_is_never_fine {
            get {
                object obj = ResourceManager.GetObject("CLAS_change_is_never_fine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_dr_sheldon_cooper_FTW {
            get {
                object obj = ResourceManager.GetObject("CLAS_dr_sheldon_cooper_FTW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_knock_knock_Penny {
            get {
                object obj = ResourceManager.GetObject("CLAS_knock_knock_Penny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_mua_ah_ah {
            get {
                object obj = ResourceManager.GetObject("CLAS_mua_ah_ah", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_not_bad_it_s_horrible {
            get {
                object obj = ResourceManager.GetObject("CLAS_not_bad_it_s_horrible", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_oouh {
            get {
                object obj = ResourceManager.GetObject("CLAS_oouh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_peace_out {
            get {
                object obj = ResourceManager.GetObject("CLAS_peace_out", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_sheldon_laugh_1 {
            get {
                object obj = ResourceManager.GetObject("CLAS_sheldon_laugh_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_sheldon_soft_kitty {
            get {
                object obj = ResourceManager.GetObject("CLAS_sheldon_soft_kitty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_there_there {
            get {
                object obj = ResourceManager.GetObject("CLAS_there_there", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLAS_we_re_taking_the_train {
            get {
                object obj = ResourceManager.GetObject("CLAS_we_re_taking_the_train", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TBBT_theme_end {
            get {
                object obj = ResourceManager.GetObject("TBBT_theme_end", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TBBT_theme_full {
            get {
                object obj = ResourceManager.GetObject("TBBT_theme_full", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_brave_leonard_song {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_brave_leonard_song", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_Engineering_oompa_loompas_of_science {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_Engineering_oompa_loompas_of_science", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_hello_honeypuffs {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_hello_honeypuffs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_i_possess_the_dna_of_leonard_nimoy {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_i_possess_the_dna_of_leonard_nimoy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_It_s_a_trap1 {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_It_s_a_trap1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_Sheldon_drunk_sings {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_Sheldon_drunk_sings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZAZZ_to_sheldon_live_long_and_prosper {
            get {
                object obj = ResourceManager.GetObject("ZAZZ_to_sheldon_live_long_and_prosper", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
