//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NascondiChiappe.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NascondiChiappe.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Album.
        /// </summary>
        public static string AddAlbum {
            get {
                return ResourceManager.GetString("AddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import some photos from your MediaLibrary or take a new one using the &quot;Take Photo&quot; button below.
        /// </summary>
        public static string AddPhotosHint {
            get {
                return ResourceManager.GetString("AddPhotosHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Album name is required.
        /// </summary>
        public static string AlbumNameRequired {
            get {
                return ResourceManager.GetString("AlbumNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to buy it!.
        /// </summary>
        public static string ClickToBuy {
            get {
                return ResourceManager.GetString("ClickToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the Album {0}?.
        /// </summary>
        public static string ConfirmAlbumDelete {
            get {
                return ResourceManager.GetString("ConfirmAlbumDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected Photo?.
        /// </summary>
        public static string ConfirmPhotoDelete {
            get {
                return ResourceManager.GetString("ConfirmPhotoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected Photos?.
        /// </summary>
        public static string ConfirmPhotosDelete {
            get {
                return ResourceManager.GetString("ConfirmPhotosDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string CopyFromMediaLibrary {
            get {
                return ResourceManager.GetString("CopyFromMediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string CopyToMediaLibrary {
            get {
                return ResourceManager.GetString("CopyToMediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Album.
        /// </summary>
        public static string DeleteAlbum {
            get {
                return ResourceManager.GetString("DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Photos.
        /// </summary>
        public static string DeleteSelectedPhotos {
            get {
                return ResourceManager.GetString("DeleteSelectedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To store more than four photos and organize them in more than one album, you have to buy the full version..
        /// </summary>
        public static string DemoInfo {
            get {
                return ResourceManager.GetString("DemoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Demo.
        /// </summary>
        public static string DemoTitle {
            get {
                return ResourceManager.GetString("DemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Album.
        /// </summary>
        public static string EditAlbum {
            get {
                return ResourceManager.GetString("EditAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save the photo right now, please try again.
        /// </summary>
        public static string ErrorSavingPhoto {
            get {
                return ResourceManager.GetString("ErrorSavingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, you cannot recover your password... I told you to remember it!.
        /// </summary>
        public static string Fucked {
            get {
                return ResourceManager.GetString("Fucked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Selected Photos.
        /// </summary>
        public static string MoveSelectedPhotos {
            get {
                return ResourceManager.GetString("MoveSelectedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to create at least one Album to use this App.
        /// </summary>
        public static string OneAlbumNecessary {
            get {
                return ResourceManager.GetString("OneAlbumNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: if you forget your password, you will not able to access to your secret photos anymore.
        ///Password recovery is not available..
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new Password must be at least {0} character lenght.
        /// </summary>
        public static string PasswordMinLenght {
            get {
                return ResourceManager.GetString("PasswordMinLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new Password does not match the confirmed Password.
        /// </summary>
        public static string PasswordsDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inserted Password is wrong.
        /// </summary>
        public static string PasswordWrong {
            get {
                return ResourceManager.GetString("PasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Photo has been copied to your MediaLibrary.
        /// </summary>
        public static string PhotoCopied {
            get {
                return ResourceManager.GetString("PhotoCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Photos has been copied to your MediaLibrary.
        /// </summary>
        public static string PhotosCopied {
            get {
                return ResourceManager.GetString("PhotosCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Photo to export.
        /// </summary>
        public static string SelectPhotoExport {
            get {
                return ResourceManager.GetString("SelectPhotoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Photos first.
        /// </summary>
        public static string SelectPhotos {
            get {
                return ResourceManager.GetString("SelectPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Photo.
        /// </summary>
        public static string ViewPhoto {
            get {
                return ResourceManager.GetString("ViewPhoto", resourceCulture);
            }
        }
    }
}
