//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathTimer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeathTimer.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often do you drink alcohol?.
        /// </summary>
        public static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m teetotal.
        /// </summary>
        public static string Alcohol1 {
            get {
                return ResourceManager.GetString("Alcohol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without exceeding.
        /// </summary>
        public static string Alcohol2 {
            get {
                return ResourceManager.GetString("Alcohol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        public static string Alcohol3 {
            get {
                return ResourceManager.GetString("Alcohol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Timerz.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many cigarettes do you smoke daily?.
        /// </summary>
        public static string Cigarettes {
            get {
                return ResourceManager.GetString("Cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often you make clinic check?.
        /// </summary>
        public static string ClinicChecks {
            get {
                return ResourceManager.GetString("ClinicChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last one was long time ago.
        /// </summary>
        public static string ClinicChecks1 {
            get {
                return ResourceManager.GetString("ClinicChecks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when I&apos;m sick.
        /// </summary>
        public static string ClinicChecks2 {
            get {
                return ResourceManager.GetString("ClinicChecks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically.
        /// </summary>
        public static string ClinicChecks3 {
            get {
                return ResourceManager.GetString("ClinicChecks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have chronic diseases?.
        /// </summary>
        public static string CronicDisease {
            get {
                return ResourceManager.GetString("CronicDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CronicDisease1 {
            get {
                return ResourceManager.GetString("CronicDisease1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, mild.
        /// </summary>
        public static string CronicDisease2 {
            get {
                return ResourceManager.GetString("CronicDisease2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, serious.
        /// </summary>
        public static string CronicDisease3 {
            get {
                return ResourceManager.GetString("CronicDisease3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday after....
        /// </summary>
        public static string DaysToBirthday {
            get {
                return ResourceManager.GetString("DaysToBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Timerz should be intended only for fun, no medical or statistical data are used to calculate the time of your death.
        ///Anyway... touch your balls!.
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use drugs?.
        /// </summary>
        public static string Drugs {
            get {
                return ResourceManager.GetString("Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never taked.
        /// </summary>
        public static string Drugs1 {
            get {
                return ResourceManager.GetString("Drugs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes.
        /// </summary>
        public static string Drugs2 {
            get {
                return ResourceManager.GetString("Drugs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually.
        /// </summary>
        public static string Drugs3 {
            get {
                return ResourceManager.GetString("Drugs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Test.
        /// </summary>
        public static string EditTest {
            get {
                return ResourceManager.GetString("EditTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t setup your birthday today or in the future..
        /// </summary>
        public static string ErrorFutureBirthday {
            get {
                return ResourceManager.GetString("ErrorFutureBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set your birthay first.
        /// </summary>
        public static string ErrorNoBirthay {
            get {
                return ResourceManager.GetString("ErrorNoBirthay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one with that birthday could be still alive....
        /// </summary>
        public static string ErrorTooOldBirthday {
            get {
                return ResourceManager.GetString("ErrorTooOldBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of diet do you follow?.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean.
        /// </summary>
        public static string Food1 {
            get {
                return ResourceManager.GetString("Food1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I eat everything.
        /// </summary>
        public static string Food2 {
            get {
                return ResourceManager.GetString("Food2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat is good.
        /// </summary>
        public static string Food3 {
            get {
                return ResourceManager.GetString("Food3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian.
        /// </summary>
        public static string Food4 {
            get {
                return ResourceManager.GetString("Food4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get other Apps from WPME.
        /// </summary>
        public static string GetOtherApps {
            get {
                return ResourceManager.GetString("GetOtherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your height (in).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your Birthday.
        /// </summary>
        public static string InsertBirthday {
            get {
                return ResourceManager.GetString("InsertBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your gender.
        /// </summary>
        public static string MaleOrFemale {
            get {
                return ResourceManager.GetString("MaleOrFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop the current music and play the gloomy background music of this app?.
        /// </summary>
        public static string PlayBackgroundMusic {
            get {
                return ResourceManager.GetString("PlayBackgroundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you do some sport?.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not so much / never.
        /// </summary>
        public static string Sports1 {
            get {
                return ResourceManager.GetString("Sports1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Sports2 {
            get {
                return ResourceManager.GetString("Sports2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Sports3 {
            get {
                return ResourceManager.GetString("Sports3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you under stress?.
        /// </summary>
        public static string Stress {
            get {
                return ResourceManager.GetString("Stress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Stress1 {
            get {
                return ResourceManager.GetString("Stress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasionally.
        /// </summary>
        public static string Stress2 {
            get {
                return ResourceManager.GetString("Stress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently.
        /// </summary>
        public static string Stress3 {
            get {
                return ResourceManager.GetString("Stress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the test!.
        /// </summary>
        public static string TakeTest {
            get {
                return ResourceManager.GetString("TakeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please respond to all questions.
        /// </summary>
        public static string TestNotCompleted {
            get {
                return ResourceManager.GetString("TestNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to Death.
        /// </summary>
        public static string TimeToDeath {
            get {
                return ResourceManager.GetString("TimeToDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your weight (lb).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will die on {0:D},
        ///at {1:N0} years.
        ///You lived {2:N2}% of your life, with {3:N0} days remaining..
        /// </summary>
        public static string WillDie {
            get {
                return ResourceManager.GetString("WillDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you still alive? It&apos;s hard to believe!.
        /// </summary>
        public static string YetAlive {
            get {
                return ResourceManager.GetString("YetAlive", resourceCulture);
            }
        }
    }
}
