//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NientePanico.Images.Flags {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlagsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlagsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NientePanico.Images.Flags.FlagsResource", typeof(FlagsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] American_Samoa__118003077309_118003077309_ {
            get {
                object obj = ResourceManager.GetObject("American_Samoa||118003077309|118003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arabia_Saudita__180010_ {
            get {
                object obj = ResourceManager.GetObject("Arabia_Saudita||180010|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Argentina__08006660171_08005550507_ {
            get {
                object obj = ResourceManager.GetObject("Argentina||08006660171|08005550507|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Australia_01180026392279_1800125440_1800120113_ {
            get {
                object obj = ResourceManager.GetObject("Australia|01180026392279|1800125440|1800120113|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Austria__0800200288_0800218235_ {
            get {
                object obj = ResourceManager.GetObject("Austria||0800200288|0800218235|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bahrain__8000006_80000087_ {
            get {
                object obj = ResourceManager.GetObject("Bahrain||8000006|80000087|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Belgio__080018397_0018003077309_ {
            get {
                object obj = ResourceManager.GetObject("Belgio||080018397|0018003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bolivia__800100188_800100173_ {
            get {
                object obj = ResourceManager.GetObject("Bolivia||800100188|800100173|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Brasile__08008913680_08008913294_ {
            get {
                object obj = ResourceManager.GetObject("Brasile||08008913680|08008913294|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Canada_01180026392279_18008472911_18003077309_ {
            get {
                object obj = ResourceManager.GetObject("Canada|01180026392279|18008472911|18003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cile__12300202136_12300202012_ {
            get {
                object obj = ResourceManager.GetObject("Cile||12300202136|12300202012|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cina__108007112911_108001107309_ {
            get {
                object obj = ResourceManager.GetObject("Cina||108007112911|108001107309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cipro___08090569_ {
            get {
                object obj = ResourceManager.GetObject("Cipro|||08090569|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Colombia__018009125713_018009121303_ {
            get {
                object obj = ResourceManager.GetObject("Colombia||018009125713|018009121303|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Costa_Rica__08000110030_08000110184_ {
            get {
                object obj = ResourceManager.GetObject("Costa_Rica||08000110030|08000110184|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Danimarca__80010277_80016098_ {
            get {
                object obj = ResourceManager.GetObject("Danimarca||80010277|80016098|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Egitto__025100200_ {
            get {
                object obj = ResourceManager.GetObject("Egitto||025100200|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Estonia__80012001_ {
            get {
                object obj = ResourceManager.GetObject("Estonia||80012001|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Filippine__180011119015_180011110061_ {
            get {
                object obj = ResourceManager.GetObject("Filippine||180011119015|180011110061|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Finlandia__0800110057_08001156234_ {
            get {
                object obj = ResourceManager.GetObject("Finlandia||0800110057|08001156234|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Francia__0800901179_0800901387_ {
            get {
                object obj = ResourceManager.GetObject("Francia||0800901179|0800901387|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Germania__08008118440_08008191040_ {
            get {
                object obj = ResourceManager.GetObject("Germania||08008118440|08008191040|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Giamaica__08008472911_08003077309_ {
            get {
                object obj = ResourceManager.GetObject("Giamaica||08008472911|08003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Giappone__00531111555_00531113886_ {
            get {
                object obj = ResourceManager.GetObject("Giappone||00531111555|00531113886|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gibilterra__88008773745966_ {
            get {
                object obj = ResourceManager.GetObject("Gibilterra||88008773745966|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Giordania__18800000_ {
            get {
                object obj = ResourceManager.GetObject("Giordania||18800000|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Grecia__00800116380304_00800118870303_ {
            get {
                object obj = ResourceManager.GetObject("Grecia||00800116380304|00800118870303|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Guam__18008472911_18003077309_ {
            get {
                object obj = ResourceManager.GetObject("Guam||18008472911|18003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Guatemala__18009990115_18009991480_ {
            get {
                object obj = ResourceManager.GetObject("Guatemala||18009990115|18009991480|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Haiti__8008472911_ {
            get {
                object obj = ResourceManager.GetObject("Haiti||8008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Honduras__8008472911_ {
            get {
                object obj = ResourceManager.GetObject("Honduras||8008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Hong_Kong__800967025_800966677_ {
            get {
                object obj = ResourceManager.GetObject("Hong_Kong||800967025|800966677|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] India__0008001001219_0008001001087_ {
            get {
                object obj = ResourceManager.GetObject("India||0008001001219|0008001001087|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Indonesia__00180319336294_00180318870623_ {
            get {
                object obj = ResourceManager.GetObject("Indonesia||00180319336294|00180318870623|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Irlanda__1800558002_1800557378_ {
            get {
                object obj = ResourceManager.GetObject("Irlanda||1800558002|1800557378|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Israele__18009411605_1809418873_ {
            get {
                object obj = ResourceManager.GetObject("Israele||18009411605|1809418873|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Kazakhstan__88001214321_ {
            get {
                object obj = ResourceManager.GetObject("Kazakhstan||88001214321|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Kenia__8666540162_ {
            get {
                object obj = ResourceManager.GetObject("Kenia||8666540162|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lettonia__800002288_ {
            get {
                object obj = ResourceManager.GetObject("Lettonia||800002288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Libano__01426801_ {
            get {
                object obj = ResourceManager.GetObject("Libano||01426801|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Liechtenstein__0800894732_0800897092_ {
            get {
                object obj = ResourceManager.GetObject("Liechtenstein||0800894732|0800897092|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lussemburgo__08002012_80024533_ {
            get {
                object obj = ResourceManager.GetObject("Lussemburgo||08002012|80024533|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Macedonia__998004288_ {
            get {
                object obj = ResourceManager.GetObject("Macedonia||998004288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Malesia__1800800159_1800804594_ {
            get {
                object obj = ResourceManager.GetObject("Malesia||1800800159|1800804594|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mauritius__011208666540165_ {
            get {
                object obj = ResourceManager.GetObject("Mauritius||011208666540165|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Messico_018001231690_0018008472911_0018003077309_ {
            get {
                object obj = ResourceManager.GetObject("Messico|018001231690|0018008472911|0018003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Monaco__0800901179_0800901387_ {
            get {
                object obj = ResourceManager.GetObject("Monaco||0800901179|0800901387|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Montserrat___18003077309_ {
            get {
                object obj = ResourceManager.GetObject("Montserrat|||18003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Norvegia__80012052_80012697_ {
            get {
                object obj = ResourceManager.GetObject("Norvegia||80012052|80012697|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Nuova_Zelanda__0800443019_0800449140_ {
            get {
                object obj = ResourceManager.GetObject("Nuova_Zelanda||0800443019|0800449140|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Olanda__08000223110_08000225821_ {
            get {
                object obj = ResourceManager.GetObject("Olanda||08000223110|08000225821|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Panama__0018001110016_0018003077309_ {
            get {
                object obj = ResourceManager.GetObject("Panama||0018001110016|0018003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Perù__8008900623_08003077309_ {
            get {
                object obj = ResourceManager.GetObject("Perù||8008900623|08003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Polonia__008001111569_008001111211_ {
            get {
                object obj = ResourceManager.GetObject("Polonia||008001111569|008001111211|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Portogallo__800811824_800811272_ {
            get {
                object obj = ResourceManager.GetObject("Portogallo||800811824|800811272|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Qatar__080001177_ {
            get {
                object obj = ResourceManager.GetObject("Qatar||080001177|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Regno_Unito__0800891725_0800964767_ {
            get {
                object obj = ResourceManager.GetObject("Regno_Unito||0800891725|0800964767|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Repubblica_Ceca__800142121_800142494_ {
            get {
                object obj = ResourceManager.GetObject("Repubblica_Ceca||800142121|800142494|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Romania__0808034288_ {
            get {
                object obj = ResourceManager.GetObject("Romania||0808034288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Russia__8108001101011_ {
            get {
                object obj = ResourceManager.GetObject("Russia||8108001101011|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Singapore__8001100344_8001100113_ {
            get {
                object obj = ResourceManager.GetObject("Singapore||8001100344|8001100113|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Slovacchia__0800000101_ {
            get {
                object obj = ResourceManager.GetObject("Slovacchia||0800000101|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Spagna__900991124_900971231_ {
            get {
                object obj = ResourceManager.GetObject("Spagna||900991124|900971231|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sud_Africa__0800990475_0800990418_ {
            get {
                object obj = ResourceManager.GetObject("Sud_Africa||0800990475|0800990418|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sud_Corea__00798119088212_00798118870823_ {
            get {
                object obj = ResourceManager.GetObject("Sud_Corea||00798119088212|00798118870823|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Svezia__020795675_020791324 {
            get {
                object obj = ResourceManager.GetObject("Svezia||020795675|020791324", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Svizzera__0800894732_0800897092 {
            get {
                object obj = ResourceManager.GetObject("Svizzera||0800894732|0800897092", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tailandia__001800115350660_001800118870663_ {
            get {
                object obj = ResourceManager.GetObject("Tailandia||001800115350660|001800118870663|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Taiwan__00801103008_00801103400_ {
            get {
                object obj = ResourceManager.GetObject("Taiwan||00801103008|00801103400|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Turchia__00800135350900_00800138870903_ {
            get {
                object obj = ResourceManager.GetObject("Turchia||00800135350900|00800138870903|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Turks_and_Caicos__018008472911_018003077309_ {
            get {
                object obj = ResourceManager.GetObject("Turks_and_Caicos||018008472911|018003077309|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ucraina__810011_ {
            get {
                object obj = ResourceManager.GetObject("Ucraina||810011|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ungheria__0680017682_0680012517_ {
            get {
                object obj = ResourceManager.GetObject("Ungheria||0680017682|0680012517|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Uruguay__0004119407915_ {
            get {
                object obj = ResourceManager.GetObject("Uruguay||0004119407915|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] USA_01180026392279_18008472911_18006278372_ {
            get {
                object obj = ResourceManager.GetObject("USA|01180026392279|18008472911|18006278372|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Venezuela__08001002167_08001002902_ {
            get {
                object obj = ResourceManager.GetObject("Venezuela||08001002167|08001002902|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Vietnam__12010288_ {
            get {
                object obj = ResourceManager.GetObject("Vietnam||12010288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
