//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiSmarrito.Images.Flags {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlagsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlagsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaiSmarrito.Images.Flags.FlagsResource", typeof(FlagsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] American_Samoa__118003077309_09485034958 {
            get {
                object obj = ResourceManager.GetObject("American_Samoa||118003077309|09485034958", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arabia_Saudita__180010_ {
            get {
                object obj = ResourceManager.GetObject("Arabia_Saudita||180010|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Argentina__08006660171_ {
            get {
                object obj = ResourceManager.GetObject("Argentina||08006660171|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Australia_01180026392279_1800125440_ {
            get {
                object obj = ResourceManager.GetObject("Australia|01180026392279|1800125440|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Austria__0800200288_ {
            get {
                object obj = ResourceManager.GetObject("Austria||0800200288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bahrain__8000006_ {
            get {
                object obj = ResourceManager.GetObject("Bahrain||8000006|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Belgio__080018397_ {
            get {
                object obj = ResourceManager.GetObject("Belgio||080018397|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bolivia__800100188_ {
            get {
                object obj = ResourceManager.GetObject("Bolivia||800100188|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Brasile__08008913680_ {
            get {
                object obj = ResourceManager.GetObject("Brasile||08008913680|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Canada_01180026392279_18008472911_ {
            get {
                object obj = ResourceManager.GetObject("Canada|01180026392279|18008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cile__12300202136_ {
            get {
                object obj = ResourceManager.GetObject("Cile||12300202136|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cina__108007112911_ {
            get {
                object obj = ResourceManager.GetObject("Cina||108007112911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Colombia__018009125713_ {
            get {
                object obj = ResourceManager.GetObject("Colombia||018009125713|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Costa_Rica__08000110030_ {
            get {
                object obj = ResourceManager.GetObject("Costa_Rica||08000110030|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cyprus___ {
            get {
                object obj = ResourceManager.GetObject("Cyprus|||", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Danimarca__80010277_ {
            get {
                object obj = ResourceManager.GetObject("Danimarca||80010277|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Egitto__025100200_ {
            get {
                object obj = ResourceManager.GetObject("Egitto||025100200|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Estonia__80012001_ {
            get {
                object obj = ResourceManager.GetObject("Estonia||80012001|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Filippine__180011119015_ {
            get {
                object obj = ResourceManager.GetObject("Filippine||180011119015|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Finlandia__0800110057_ {
            get {
                object obj = ResourceManager.GetObject("Finlandia||0800110057|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Francia__0800901179_ {
            get {
                object obj = ResourceManager.GetObject("Francia||0800901179|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Germania__08008118440_ {
            get {
                object obj = ResourceManager.GetObject("Germania||08008118440|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Giamaica__08008472911_ {
            get {
                object obj = ResourceManager.GetObject("Giamaica||08008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Giappone__00531111555_ {
            get {
                object obj = ResourceManager.GetObject("Giappone||00531111555|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gibilterra__88008773745966_ {
            get {
                object obj = ResourceManager.GetObject("Gibilterra||88008773745966|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Giordania__18800000_ {
            get {
                object obj = ResourceManager.GetObject("Giordania||18800000|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Grecia__00800116380304_ {
            get {
                object obj = ResourceManager.GetObject("Grecia||00800116380304|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Guam__18008472911_ {
            get {
                object obj = ResourceManager.GetObject("Guam||18008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Guatemala__18009990115_ {
            get {
                object obj = ResourceManager.GetObject("Guatemala||18009990115|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Haiti__8008472911_ {
            get {
                object obj = ResourceManager.GetObject("Haiti||8008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Honduras__8008472911_ {
            get {
                object obj = ResourceManager.GetObject("Honduras||8008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Hong_Kong__800967025_ {
            get {
                object obj = ResourceManager.GetObject("Hong_Kong||800967025|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] India__0008001001219_ {
            get {
                object obj = ResourceManager.GetObject("India||0008001001219|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Indonesia__00180319336294_ {
            get {
                object obj = ResourceManager.GetObject("Indonesia||00180319336294|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Irlanda__1800558002_ {
            get {
                object obj = ResourceManager.GetObject("Irlanda||1800558002|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Israel__18009411605_ {
            get {
                object obj = ResourceManager.GetObject("Israel||18009411605|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Kazakhstan__88001214321_ {
            get {
                object obj = ResourceManager.GetObject("Kazakhstan||88001214321|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Kenia__8666540162_ {
            get {
                object obj = ResourceManager.GetObject("Kenia||8666540162|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lettonia__800002288_ {
            get {
                object obj = ResourceManager.GetObject("Lettonia||800002288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Libano__01426801_ {
            get {
                object obj = ResourceManager.GetObject("Libano||01426801|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Liechtenstein__0800894732_ {
            get {
                object obj = ResourceManager.GetObject("Liechtenstein||0800894732|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lussemburgo__08002012_ {
            get {
                object obj = ResourceManager.GetObject("Lussemburgo||08002012|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Macedonia__998004288_ {
            get {
                object obj = ResourceManager.GetObject("Macedonia||998004288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Malesia__1800800159_ {
            get {
                object obj = ResourceManager.GetObject("Malesia||1800800159|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mauritius__011208666540165_ {
            get {
                object obj = ResourceManager.GetObject("Mauritius||011208666540165|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Messico_018001231690_0018008472911_ {
            get {
                object obj = ResourceManager.GetObject("Messico|018001231690|0018008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Monaco__0800901179_ {
            get {
                object obj = ResourceManager.GetObject("Monaco||0800901179|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Montserrat___ {
            get {
                object obj = ResourceManager.GetObject("Montserrat|||", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Norvegia__80012052_ {
            get {
                object obj = ResourceManager.GetObject("Norvegia||80012052|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Nuova_Zelanda__0800443019_ {
            get {
                object obj = ResourceManager.GetObject("Nuova_Zelanda||0800443019|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Olanda__08000223110_ {
            get {
                object obj = ResourceManager.GetObject("Olanda||08000223110|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Panama__0018001110016_ {
            get {
                object obj = ResourceManager.GetObject("Panama||0018001110016|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Perù__8008900623_ {
            get {
                object obj = ResourceManager.GetObject("Perù||8008900623|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Polonia__008001111569_ {
            get {
                object obj = ResourceManager.GetObject("Polonia||008001111569|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Portogallo__800811824_ {
            get {
                object obj = ResourceManager.GetObject("Portogallo||800811824|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Qatar__080001177_ {
            get {
                object obj = ResourceManager.GetObject("Qatar||080001177|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Regno_Unito__0800891725_ {
            get {
                object obj = ResourceManager.GetObject("Regno_Unito||0800891725|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Repubblica_Ceca__800142121_ {
            get {
                object obj = ResourceManager.GetObject("Repubblica_Ceca||800142121|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Romania__0808034288_ {
            get {
                object obj = ResourceManager.GetObject("Romania||0808034288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Russia__8108001101011_ {
            get {
                object obj = ResourceManager.GetObject("Russia||8108001101011|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Singapore__8001100344_ {
            get {
                object obj = ResourceManager.GetObject("Singapore||8001100344|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Slovacchia__0800000101_ {
            get {
                object obj = ResourceManager.GetObject("Slovacchia||0800000101|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Spagna__900991124_ {
            get {
                object obj = ResourceManager.GetObject("Spagna||900991124|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sud_Africa__0800990475_ {
            get {
                object obj = ResourceManager.GetObject("Sud_Africa||0800990475|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sud_Corea__00798119088212_ {
            get {
                object obj = ResourceManager.GetObject("Sud_Corea||00798119088212|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Svezia__020795675_ {
            get {
                object obj = ResourceManager.GetObject("Svezia||020795675|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Svizzera__0800894732_ {
            get {
                object obj = ResourceManager.GetObject("Svizzera||0800894732|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tailandia__001800115350660_ {
            get {
                object obj = ResourceManager.GetObject("Tailandia||001800115350660|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Taiwan__00801103008_ {
            get {
                object obj = ResourceManager.GetObject("Taiwan||00801103008|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Turchia__00800135350900_ {
            get {
                object obj = ResourceManager.GetObject("Turchia||00800135350900|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Turks_and_Caicos__018008472911_ {
            get {
                object obj = ResourceManager.GetObject("Turks_and_Caicos||018008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ucraina__810011_ {
            get {
                object obj = ResourceManager.GetObject("Ucraina||810011|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ungheria__0680017682_ {
            get {
                object obj = ResourceManager.GetObject("Ungheria||0680017682|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Uruguay__0004119407915_ {
            get {
                object obj = ResourceManager.GetObject("Uruguay||0004119407915|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] USA_01180026392279_18008472911_ {
            get {
                object obj = ResourceManager.GetObject("USA|01180026392279|18008472911|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Venezuela__08001002167_ {
            get {
                object obj = ResourceManager.GetObject("Venezuela||08001002167|", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Vietnam__12010288_ {
            get {
                object obj = ResourceManager.GetObject("Vietnam||12010288|", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
