//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiSmarrito.Images.Flags {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlagsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlagsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaiSmarrito.Images.Flags.FlagsResource", typeof(FlagsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] American_Samoa {
            get {
                object obj = ResourceManager.GetObject("American_Samoa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Argentina {
            get {
                object obj = ResourceManager.GetObject("Argentina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Australia {
            get {
                object obj = ResourceManager.GetObject("Australia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Austria {
            get {
                object obj = ResourceManager.GetObject("Austria", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bahrain {
            get {
                object obj = ResourceManager.GetObject("Bahrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Belgium {
            get {
                object obj = ResourceManager.GetObject("Belgium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bolivia {
            get {
                object obj = ResourceManager.GetObject("Bolivia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Brazil {
            get {
                object obj = ResourceManager.GetObject("Brazil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Canada {
            get {
                object obj = ResourceManager.GetObject("Canada", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Chile {
            get {
                object obj = ResourceManager.GetObject("Chile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] China {
            get {
                object obj = ResourceManager.GetObject("China", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Colombia {
            get {
                object obj = ResourceManager.GetObject("Colombia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Costa_Rica {
            get {
                object obj = ResourceManager.GetObject("Costa_Rica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cyprus {
            get {
                object obj = ResourceManager.GetObject("Cyprus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Czech_Republic {
            get {
                object obj = ResourceManager.GetObject("Czech_Republic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Denmark {
            get {
                object obj = ResourceManager.GetObject("Denmark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Egypt {
            get {
                object obj = ResourceManager.GetObject("Egypt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Estonia {
            get {
                object obj = ResourceManager.GetObject("Estonia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Finland {
            get {
                object obj = ResourceManager.GetObject("Finland", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] France {
            get {
                object obj = ResourceManager.GetObject("France", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Germany {
            get {
                object obj = ResourceManager.GetObject("Germany", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gibraltar {
            get {
                object obj = ResourceManager.GetObject("Gibraltar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Greece {
            get {
                object obj = ResourceManager.GetObject("Greece", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Guam {
            get {
                object obj = ResourceManager.GetObject("Guam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Guatemala {
            get {
                object obj = ResourceManager.GetObject("Guatemala", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Haiti {
            get {
                object obj = ResourceManager.GetObject("Haiti", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Honduras {
            get {
                object obj = ResourceManager.GetObject("Honduras", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Hong_Kong {
            get {
                object obj = ResourceManager.GetObject("Hong_Kong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Hungary {
            get {
                object obj = ResourceManager.GetObject("Hungary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] India {
            get {
                object obj = ResourceManager.GetObject("India", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Indonesia {
            get {
                object obj = ResourceManager.GetObject("Indonesia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ireland {
            get {
                object obj = ResourceManager.GetObject("Ireland", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Israel {
            get {
                object obj = ResourceManager.GetObject("Israel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Jamaica {
            get {
                object obj = ResourceManager.GetObject("Jamaica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Japan {
            get {
                object obj = ResourceManager.GetObject("Japan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Jordan {
            get {
                object obj = ResourceManager.GetObject("Jordan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Kazakhstan {
            get {
                object obj = ResourceManager.GetObject("Kazakhstan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Kenya {
            get {
                object obj = ResourceManager.GetObject("Kenya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Korea {
            get {
                object obj = ResourceManager.GetObject("Korea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Latvia {
            get {
                object obj = ResourceManager.GetObject("Latvia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lebanon {
            get {
                object obj = ResourceManager.GetObject("Lebanon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Liechtenstein {
            get {
                object obj = ResourceManager.GetObject("Liechtenstein", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Luxembourg {
            get {
                object obj = ResourceManager.GetObject("Luxembourg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Macedonia {
            get {
                object obj = ResourceManager.GetObject("Macedonia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Malaysia {
            get {
                object obj = ResourceManager.GetObject("Malaysia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mauritius {
            get {
                object obj = ResourceManager.GetObject("Mauritius", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mexico {
            get {
                object obj = ResourceManager.GetObject("Mexico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Monaco {
            get {
                object obj = ResourceManager.GetObject("Monaco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Montserrat {
            get {
                object obj = ResourceManager.GetObject("Montserrat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Netherlands {
            get {
                object obj = ResourceManager.GetObject("Netherlands", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] New_Zealand {
            get {
                object obj = ResourceManager.GetObject("New_Zealand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Norway {
            get {
                object obj = ResourceManager.GetObject("Norway", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Panama {
            get {
                object obj = ResourceManager.GetObject("Panama", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Peru {
            get {
                object obj = ResourceManager.GetObject("Peru", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Philippines {
            get {
                object obj = ResourceManager.GetObject("Philippines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Poland {
            get {
                object obj = ResourceManager.GetObject("Poland", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Portugal {
            get {
                object obj = ResourceManager.GetObject("Portugal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Qatar {
            get {
                object obj = ResourceManager.GetObject("Qatar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Romania {
            get {
                object obj = ResourceManager.GetObject("Romania", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Russia {
            get {
                object obj = ResourceManager.GetObject("Russia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Saudi_Arabia {
            get {
                object obj = ResourceManager.GetObject("Saudi_Arabia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Singapore {
            get {
                object obj = ResourceManager.GetObject("Singapore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Slovakia {
            get {
                object obj = ResourceManager.GetObject("Slovakia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] South_Africa {
            get {
                object obj = ResourceManager.GetObject("South_Africa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Spain {
            get {
                object obj = ResourceManager.GetObject("Spain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sweden {
            get {
                object obj = ResourceManager.GetObject("Sweden", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Switzerland {
            get {
                object obj = ResourceManager.GetObject("Switzerland", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Taiwan {
            get {
                object obj = ResourceManager.GetObject("Taiwan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Thailand {
            get {
                object obj = ResourceManager.GetObject("Thailand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Turkey {
            get {
                object obj = ResourceManager.GetObject("Turkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Turks_and_Caicos_Islands_png {
            get {
                object obj = ResourceManager.GetObject("Turks_and_Caicos_Islands_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ukraine {
            get {
                object obj = ResourceManager.GetObject("Ukraine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] United_Kingdom {
            get {
                object obj = ResourceManager.GetObject("United_Kingdom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] United_States {
            get {
                object obj = ResourceManager.GetObject("United_States", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Uruguay {
            get {
                object obj = ResourceManager.GetObject("Uruguay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Venezuela {
            get {
                object obj = ResourceManager.GetObject("Venezuela", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Vietnam {
            get {
                object obj = ResourceManager.GetObject("Vietnam", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
