//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathTimerz.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HealthAdvices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HealthAdvices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeathTimerz.Localization.HealthAdvices", typeof(HealthAdvices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eat less.
        /// </summary>
        internal static string Advice1 {
            get {
                return ResourceManager.GetString("Advice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are stupid you live less.
        /// </summary>
        internal static string Advice2 {
            get {
                return ResourceManager.GetString("Advice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t eat fat.
        /// </summary>
        internal static string Advice3 {
            get {
                return ResourceManager.GetString("Advice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make exercise every day.
        /// </summary>
        internal static string Advice4 {
            get {
                return ResourceManager.GetString("Advice4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to swim.
        /// </summary>
        internal static string Advice5 {
            get {
                return ResourceManager.GetString("Advice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sex.
        /// </summary>
        internal static string Advice6 {
            get {
                return ResourceManager.GetString("Advice6", resourceCulture);
            }
        }
    }
}
