//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathTimerz.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Test2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeathTimerz.Localization.Test2", typeof(Test2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which animal do you prefer?.
        /// </summary>
        internal static string Animal {
            get {
                return ResourceManager.GetString("Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        internal static string Animal1 {
            get {
                return ResourceManager.GetString("Animal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        internal static string Animal2 {
            get {
                return ResourceManager.GetString("Animal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string Animal3 {
            get {
                return ResourceManager.GetString("Animal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you feeling lonley, shy or isolated?.
        /// </summary>
        internal static string ForeverAlone {
            get {
                return ResourceManager.GetString("ForeverAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I have friends.
        /// </summary>
        internal static string ForeverAlone1 {
            get {
                return ResourceManager.GetString("ForeverAlone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lately.
        /// </summary>
        internal static string ForeverAlone2 {
            get {
                return ResourceManager.GetString("ForeverAlone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since adolesence.
        /// </summary>
        internal static string ForeverAlone3 {
            get {
                return ResourceManager.GetString("ForeverAlone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In my entire life.
        /// </summary>
        internal static string ForeverAlone4 {
            get {
                return ResourceManager.GetString("ForeverAlone4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you suffer Headaches?.
        /// </summary>
        internal static string Headache {
            get {
                return ResourceManager.GetString("Headache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost never.
        /// </summary>
        internal static string Headache1 {
            get {
                return ResourceManager.GetString("Headache1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few times in a year.
        /// </summary>
        internal static string Headache2 {
            get {
                return ResourceManager.GetString("Headache2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least once a month.
        /// </summary>
        internal static string Headache3 {
            get {
                return ResourceManager.GetString("Headache3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least once a week.
        /// </summary>
        internal static string Headache4 {
            get {
                return ResourceManager.GetString("Headache4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have insomnia or do you oversleep?.
        /// </summary>
        internal static string Insomnia {
            get {
                return ResourceManager.GetString("Insomnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problems, I sleep about 8 ours a day.
        /// </summary>
        internal static string Insomnia1 {
            get {
                return ResourceManager.GetString("Insomnia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I sleep less than 8 hours a day.
        /// </summary>
        internal static string Insomnia2 {
            get {
                return ResourceManager.GetString("Insomnia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I always take a nap after launch.
        /// </summary>
        internal static string Insomnia3 {
            get {
                return ResourceManager.GetString("Insomnia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have serious difficulties to fall asleep every night.
        /// </summary>
        internal static string Insomnia4 {
            get {
                return ResourceManager.GetString("Insomnia4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Painic1 {
            get {
                return ResourceManager.GetString("Painic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you panick attacks for no apparent reason?.
        /// </summary>
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes.
        /// </summary>
        internal static string Panic2 {
            get {
                return ResourceManager.GetString("Panic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Often.
        /// </summary>
        internal static string Panic3 {
            get {
                return ResourceManager.GetString("Panic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string Panic4 {
            get {
                return ResourceManager.GetString("Panic4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you afraid of a particular animal, or by doing some activity?.
        /// </summary>
        internal static string Phobia {
            get {
                return ResourceManager.GetString("Phobia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Phobia1 {
            get {
                return ResourceManager.GetString("Phobia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Phobia2 {
            get {
                return ResourceManager.GetString("Phobia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much do you self esteem?.
        /// </summary>
        internal static string SelfEsteem {
            get {
                return ResourceManager.GetString("SelfEsteem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am less than a 0.
        /// </summary>
        internal static string SelfEsteem1 {
            get {
                return ResourceManager.GetString("SelfEsteem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string SelfEsteem2 {
            get {
                return ResourceManager.GetString("SelfEsteem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am realistic.
        /// </summary>
        internal static string SelfEsteem3 {
            get {
                return ResourceManager.GetString("SelfEsteem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string SelfEsteem4 {
            get {
                return ResourceManager.GetString("SelfEsteem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am the best.
        /// </summary>
        internal static string SelfEsteem5 {
            get {
                return ResourceManager.GetString("SelfEsteem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you under stress?.
        /// </summary>
        internal static string Stress {
            get {
                return ResourceManager.GetString("Stress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string Stress1 {
            get {
                return ResourceManager.GetString("Stress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasionally.
        /// </summary>
        internal static string Stress2 {
            get {
                return ResourceManager.GetString("Stress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently.
        /// </summary>
        internal static string Stress3 {
            get {
                return ResourceManager.GetString("Stress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string Stress4 {
            get {
                return ResourceManager.GetString("Stress4", resourceCulture);
            }
        }
    }
}
