//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathTimerz.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Test1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeathTimerz.Localization.Test1", typeof(Test1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often do you drink alcohol?.
        /// </summary>
        internal static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m teetotal.
        /// </summary>
        internal static string Alcohol1 {
            get {
                return ResourceManager.GetString("Alcohol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without exceeding.
        /// </summary>
        internal static string Alcohol2 {
            get {
                return ResourceManager.GetString("Alcohol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day.
        /// </summary>
        internal static string Alcohol3 {
            get {
                return ResourceManager.GetString("Alcohol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many cigarettes do you smoke daily?.
        /// </summary>
        internal static string Cigarettes {
            get {
                return ResourceManager.GetString("Cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often you make clinic check?.
        /// </summary>
        internal static string ClinicChecks {
            get {
                return ResourceManager.GetString("ClinicChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last one was long time ago.
        /// </summary>
        internal static string ClinicChecks1 {
            get {
                return ResourceManager.GetString("ClinicChecks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when I&apos;m sick.
        /// </summary>
        internal static string ClinicChecks2 {
            get {
                return ResourceManager.GetString("ClinicChecks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically.
        /// </summary>
        internal static string ClinicChecks3 {
            get {
                return ResourceManager.GetString("ClinicChecks3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have chronic diseases?.
        /// </summary>
        internal static string CronicDisease {
            get {
                return ResourceManager.GetString("CronicDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CronicDisease1 {
            get {
                return ResourceManager.GetString("CronicDisease1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, mild.
        /// </summary>
        internal static string CronicDisease2 {
            get {
                return ResourceManager.GetString("CronicDisease2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, serious.
        /// </summary>
        internal static string CronicDisease3 {
            get {
                return ResourceManager.GetString("CronicDisease3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use drugs?.
        /// </summary>
        internal static string Drugs {
            get {
                return ResourceManager.GetString("Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never taked.
        /// </summary>
        internal static string Drugs1 {
            get {
                return ResourceManager.GetString("Drugs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes.
        /// </summary>
        internal static string Drugs2 {
            get {
                return ResourceManager.GetString("Drugs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually.
        /// </summary>
        internal static string Drugs3 {
            get {
                return ResourceManager.GetString("Drugs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of diet do you follow?.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean.
        /// </summary>
        internal static string Food1 {
            get {
                return ResourceManager.GetString("Food1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I eat everything.
        /// </summary>
        internal static string Food2 {
            get {
                return ResourceManager.GetString("Food2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat is good.
        /// </summary>
        internal static string Food3 {
            get {
                return ResourceManager.GetString("Food3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian.
        /// </summary>
        internal static string Food4 {
            get {
                return ResourceManager.GetString("Food4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your height (in).
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you do some sport?.
        /// </summary>
        internal static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not so much / never.
        /// </summary>
        internal static string Sports1 {
            get {
                return ResourceManager.GetString("Sports1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Sports2 {
            get {
                return ResourceManager.GetString("Sports2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string Sports3 {
            get {
                return ResourceManager.GetString("Sports3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your weight (lb).
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
